### ISSUE TITLE
c4_api выгрузка только правил или объектов.

### ISSUE THREAD

**Issue by parashu-rama** [itseccode/c4_tools#2]
Добрый день!

Есть ли возможность выгружать только правила или только сетевые объекты?

В библиотеке

/config/{master_uuid}/export-config-for-cgw/{hwserial}?view=full

Кроме опции full есть ли другие опции?

**Comment by itseccode** [comment]
Пока выгружаем конфиг полностью. Подумаем, как сделать, но отдельным инструментом.

По опциям фильтрации - выясним.
